# -*- coding: utf-8 -*-
"""classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vc0ZwdGdZjjb03qxZgZpNKUIymNfFha5

Classes
"""

# Criando uma classe chamada Livro
class Livro():
  def __init__(self): # método 
    self.titulo = 'O monge e o executivo' # atributo do objeto
    self.isbn = 9988888  # atributo do objeto
    print('Construtor chamado para criar o objeto desta classe')

  def imprime(self): # método
    print("Foi criado o livro %s e ISBN %d" %(self.titulo, self.isbn))

# Criando uma instância da classe Livro
Livro1 = Livro()

# Tipo do Objeto Livro1
type(Livro1)

# Atributo do objeto Livro1
Livro1.titulo

# Método do objeto Livro1
Livro1.imprime()

# Criando a classe Livro com parâmetros no método construtor
class Livro():
  def __init__(self,titulo, isbn): 
    self.titulo = titulo
    self.isbn = isbn
    print("Construtor chamado para criar um objeto dessa classe.")

  def imprime(self, titulo, isbn):
    print("Este é o livro%s e ISBN %d" %(titulo, isbn))

# Criando o objeto Livro2 que é uma instância da classe Livro
Livro2 = Livro("A Menina que Roubava Livros", 77886611)

Livro2.titulo

Livro2.isbn

# Método do objeto Livro2
Livro2.imprime("A Menina que Roubava Livros", 77886611)

# Criando a classe cachorro
class Cachorro():
  def __init__(self, raca):
    self.raca = raca
    print("Contrutor chamado paracriar um objeto desta classe.")

# Criando um objeto a partir da classe cachorro
Rex = Cachorro(raca = "Labrador")

# Criando um objeto a partir da classe cachorro
Golias = Cachorro(raca = "Huskie")

# Atributo da classe cachorro, utilizado pelo objeto criado
Rex.raca

Golias.raca