# -*- coding: utf-8 -*-
"""datetime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mNX34WqBIvzC0PGM8OQecon6DJiDd5k6
"""

import datetime

agora = datetime.datetime.now()

print(agora)

t = datetime.time(18, 6, 35)

print(t)

print('Hora: ', t.hour)
print('Minuto: ', t.minute)
print('Segundo: ', t.second)
print('Microsegundo: ', t.microsecond)

print(datetime.time.min)

hoje = datetime.date.today()

print(hoje)

print(hoje)
print('ctime: ', hoje.ctime())
print('Ano: ', hoje.year)
print('Mês: ', hoje.month)
print('Dia: ', hoje.day)

d1 = datetime.date(2015, 4, 10)
print('d1: ', d1)

d2 = datetime.date(2021, 11, 24)
print('d2: ', d2)

# Diferença em dias entre duas datas
d2 -d1