# -*- coding: utf-8 -*-
"""dicionarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1odP0VnrX3MgyJkiCCp006Lv6ADrkIX5G
"""

# isso é uma lista.
estudantes_list = ['Matheus', 24, 'Fernanda', 22, 'Tamires', 26,'Cristiano', 25]
print(estudantes_list)

# isso é um dicinário.
estudantes_dict = {"Matheus": 24, "Fernanda": 22, "Tamires": 26,"Cristiano": 25}
print(estudantes_dict)

estudantes_dict["Matheus"]

estudantes_dict ["Pedro"] = 23

estudantes_dict["Pedro"]

estudantes_dict["Tamires"]

estudantes_dict.clear()

estudantes_dict

del estudantes_dict

estudantes_dict

estudantes = {"Mateus":24, "Fernanda":22, "Tamires":26, "Cristiano":25}

estudantes

len(estudantes)

estudantes.keys()

estudantes.values()

estudantes2 ={"Maria": 27, "Erica": 28, "Milton":26}

estudantes2

estudantes.update(estudantes2)

estudantes

dict1 = {}

dict1["Key_one"] = 2

print(dict1)

dict1 [10] = 5

dict1

dict1 [8.2] = "Python"

print(dict1)

dict1["teste"] = 6

print(dict1)

dict1 ={}

dict1

dict1["teste"]= 10

dict1["key"]= "teste"

dict1

dict2 ={}

dict2["key1"]= "Big data"

dict2 ["key2"] = 10

dict2 ["key3"] = 5.6

dict2

a = dict2 ["key1"]

b = dict2 ["key2"]

c = dict2 ["key3"]

a, b, c

# dicionario de listas:

dict3 = {"key1": 1230, "key2": [22, 453, 73.4], "key3": ["leite", "maca", "banana"]}

dict3

dict3["key3"]

dict3 ["key3"][0].upper()

var1 = dict3["key2"][0] - 2

var1

dict3 ["key2"][0] -= 2

dict3

"""**Criando dicionários aninhados**"""

dict_aninhado = {"key1":{"key2_aninhada":{"key3_aninhada": "Dicionário aninhado em Python"}}}

dict_aninhado

dict_aninhado["key1"]["key2_aninhada"]["key3_aninhada"]