# -*- coding: utf-8 -*-
"""exercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iD4Lhvyl2gJkWikLgtuM7CztlQQq3UQc
"""

# imprimir na tela a sequencia de numeros de 1 a 10. Armazenar em lista.
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(numeros)

# imprimir uma lista com 5 objetos.
lista_objetos = [ "quadro", "vaso", "mesa", "bola", "revista"]
print(lista_objetos)

# crie duas strings e concatene em uma terceira string.
string1 = ("Python é uma linguagem de alto nível")
string2 = (" e uma das mais usadas no mundo.")
string3 = string1 + string2
print(string3)

# Exercício 4 - Crie uma tupla com os seguintes elementos: 1, 2, 2, 3, 4, 4, 4, 5 e depois utilize a função count do 
# objeto tupla para verificar quantas vezes o número 4 aparece na tupla
tupla1 = ('1', '2', '2', '3', '4', '4', '4', '5')
tupla1.count('4')

# Exercício 5 - Crie um dicionário vazio e imprima na tela
dicionario1 ={}
print(dicionario1)

# Exercício 6 - Crie um dicionário com 3 chaves e 3 valores e imprima na tela
dicionario1["Carro_1"] = "15 km"
dicionario1["Carro_2"] = "36 km"
dicionario1["Carro_3"] = "85 km"
print(dicionario1)

# Exercício 7 - Adicione mais um elemento ao dicionário criado no exercício anterior e imprima na tela
dicionario1["Carro_4"] = "120 km"
dicionario1["Carro_4"]

# Exercício 8 - Crie um dicionário com 3 chaves e 3 valores. Um dos valores deve ser uma lista de 2 elementos numéricos. 
# Imprima o dicionário na tela.
dic1 = {'Pais': 'Brasil', 'População': 200, 'Constituição': 1988}
print(dic1)

# Exercício 9 - Crie uma lista de 4 elementos. O primeiro elemento deve ser uma string, 
# o segundo uma tupla de 2 elementos, o terceiro um dcionário com 2 chaves e 2 valores e 
# o quarto elemento um valor do tipo float.
# Imprima a lista na tela.

corrida = "Formula 1 - 2021"
equipes = ("Mercedes", "Redbull")
posicao = {'1º': 'Verstappen', "2º": 'Hamilton'}
lideranca = 287.50
lista_exercicio9 = [corrida, equipes, posicao, lideranca]
print(lista_exercicio9)

# Exercício 10 - Considere a string abaixo. Imprima na tela apenas os caracteres da posição 1 a 18.
frase = 'Cientista de Dados é o profissional mais sexy do século XXI'
frase[0:18]