# -*- coding: utf-8 -*-
"""filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tlaWRZ2pzozuvvuS6MNpiL3NW2O5Xulj

Filter
"""

# criando uma função:
def verificaPar(num):
  if num % 2 == 0:
    return True
  else:
    return False

# Chamando a função, passando um número e verificando se é par ou impar. Caso par retorna True e impar Falso.

verificaPar(34)

lista = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]

lista

filter(verificaPar, lista)

list(filter(verificaPar, lista))

list(filter(lambda x: x % 2 ==0 , lista))

list(filter(lambda num: num > 8, lista))