# -*- coding: utf-8 -*-
"""lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OiNs4i3Ouc5aBPui2bqEGicAwMWBIZwy

Expressões Lambda
"""

# Definindo uma função - 3 linhas de código
def potencia(num):
  result = num**2
  return result

potencia(5)

# Definindo uma função - 2 linhas de código
def potencia(num):
  return num**2

potencia(32)

# Definindo uma função - 1 linha de código
def potencia(num): return num**2

potencia(15)

# Definindo uma expressão lambda
potencia = lambda num: num**2

potencia(5)

# Lembre: operadores de comparação retornam boolean, true or false
par = lambda x: x%2==0

par(7)

par(10)

first = lambda s: s[0]

first('Python')

reverso = lambda s: s[::-1]

reverso('Python')

addNum = lambda x,y: x+y

addNum(2,3)