# -*- coding: utf-8 -*-
"""list-comprehension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BjLZKHRbxHzryO8_yFjybJH_K9vodIHK

List Comprehension
"""

# Retorna cada caractere em uma sequencia de caracteres:
lst = [x for x in 'python']

#check:
lst

type(lst)

# Variável x elevada ao quadrado para um range de números e retornar uma lista
lst = [x**2 for x in range(0,11)]

lst

# Verificar os números pares em um range de números

lst = [x for x in range(11) if x % 2 == 0]

lst

# Converter Celsius para Fahrenheit
celsius = [0,10,20.1,34.5]
fahrenheit = [((float(9)/ 5)* temp + 32) for temp in celsius ]
fahrenheit

# operações aninhadas
lst = [x**2 for x in [x**2 for x in range(11)]]

lst