# -*- coding: utf-8 -*-
"""listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1shuLcFxiAJKe2LxcO0NqjbZJzK6pWHEy
"""

# criando uma lista:
listadomercado = ["ovos, farinha, leite, maças"]
print(listadomercado)

listadomercado2 = ["ovos", "farinha","leite","maças"]
listadomercado2

# listas permitem mais de um tipo de variável.
lista3 = [12, 100, "universidade"]
print(lista3)

# Atribuindo cada elemento da lista a uma variável
item1 = lista3[0]
item2 = lista3[1]
item3 = lista3[2]
print(item2, item3)

"""Atualizando itens da lista:"""

# Imprimindo um item da lista
listadomercado2[2]

# Atualizando um item.
listadomercado2[2] = "chocolate"
print(listadomercado2)

"""Deletando elementos da lista:"""

# Deletando um item da lista.
del listadomercado2[3]
print(listadomercado2)

"""Listas de listas (Listas aninhadas):"""

# Lista de listas = matrizes em Python.
listas = [[1, 2, 3], [10, 15, 14], [10.2, 7.6, 2.8]]
print(listas)

# Atribuindo um item da lista a uma variável:
a = listas[0]
b = listas[1]
c = a[0]
print(a,b,c)

list1 = listas[2]
print(list1)

valor_1_0 = list1[0]
print(valor_1_0)

valor_1_1 = list1[1]
print(valor_1_1)

"""Operações com listas"""

# Criando uma lista aninhada
listas2 = [[1,2,3,],[4,5,6],[7,8,9,10]]
print(listas2)
# Separando elementos dentro de listas
a = listas2[0][0]
print(a)
b = listas[1][0]
print(b)
# Soma de lista + variável
c = listas2[0][2] + 10
print(c)
d = 15
e = d *listas2[0][1]
print(e)

"""Concatenando listas:"""

lista_s1 = [30, 35, 40]
print(lista_s1)
lista_s2 = [45, 50, 55]
print(lista_s2)
lista_total = lista_s1 +lista_s2
print(lista_total)

"""Operador in:"""

lista_teste_op = [100, 2, -5, 2.3]
print(10 in lista_teste_op)
print(100 in lista_teste_op)

"""Funções Built-in:"""

len(lista_teste_op) # Retorna o tamanho da lista.

max(lista_teste_op) # Retorna o maior valor da lista.

min(lista_teste_op) # Retorna o menor valor da lista.

print(listadomercado2)
listadomercado2.append('manteiga')
print(listadomercado2)
listadomercado2.append('manteiga')
print(listadomercado2)
listadomercado2.count('manteiga')

# Inserindo elementos numa lista vazia.
lista_vazia = []
print(lista_vazia)
type(lista_vazia)
lista_vazia.append(10)
lista_vazia.append(50)
print(lista_vazia)

# Copiando os itens de uma lista para outra
old_lista = [1,2,5,10]
new_lista = []

for item in old_lista:
  new_lista.append(item)
new_lista
f = [20,30]
f.append(40)
print(f)

cidades=["Recife", "Salvador", "Rio de Janeiro", "São Paulo"]
cidades.extend(['Fortaleza', 'Palmas'])
print(cidades)
cidades.index('Fortaleza')
cidades.insert(2, 150)
print(cidades)
cidades.remove(150)
print(cidades)

x = [2,8,4,10,6,14]
x.sort()
x