# -*- coding: utf-8 -*-
"""loop-for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1huyFFBtR-p-a8qZtrca_UAOo_8NnUr0b
"""

#criando uma tupla e imprimindo cada um dos valores

tp = (2,3,4)
for i in tp:
  print(i)

# criando uma lista e imprimindo cada um dos valores

ListaDoMercado = ["Arroz", "Feijão", "Açúcar", "Óleo"]
for i in ListaDoMercado:
  print(i)

# imprimindo valores num intervalo de 0 a 5 (exclusive)

for contador in range (0,5):
  print(contador)

# imprimindo na tela os números pares da lista de números:

lista = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for num in lista:
  if num % 2 == 0:
    print(num)

# listando os números no intervalo de 0 a 101, com incremento de 2:

for i in range(0,101,2):
  print(i)

# strings támbem são sequencias:

for caracter in 'Python é uma linguagem divertida.':
  print(caracter)

"""Loops Aninhados"""

# Loops aninhados:

for i in range(0,5):
  for i in range(0,5):
    print(i)

# Operando valores de uma lista com loop for:

listaB = [32,53,85,10,15,17,19]
soma = 0
for i in listaB:
  doble_i = i * 2
  soma += doble_i
print(soma)

# loop em lista de listas:

listas = [[1,2,3],[23,33,43],[10.2,20.4, 30.6]]
for valor in listas:
  print(valor)

# contando os valores de uma lista:

lista = [5,6,10,13,17]
count = 0
for i in lista:
  count += 1
print(count)

# contando o número de colunas:

lst = [[1,2,4],[3,4,5],[5,6,7]]
primeira_linha = lst[0]
count = 0
for colum in primeira_linha:
  count = count + 1
print(count)

# pesquisando em listas:

listaC = [5,6,7,10,50]

# loop atrávez da lista:

for i in listaC:
  if i == 5:
    print("Número encontrado")

# Listando as chaves de um dicionário:

dict = {'K1': "Python",'K2': "R",'K3': "Scala"}
for item in dict:
  print(item)

# Imprimindo chave e valor do dicionário. Usando o método items() para retornar os itens de um dicionário:

for k,v in dict.items():
  print(k,v)