# -*- coding: utf-8 -*-
"""metodos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Ckaaewp3ejk7oMOzuRHyL4OHHAVKVIZ

Metodos
"""

# Criando uma lista
lst = [100, -2, 12, 65, 0]

# Usando um método do objeto lista
lst.append(10)

# Imprimindo a lista
lst

# Usando um método do objeto lista
lst.count(10)

# A função help() explica como utilizar cada método de um objeto
help(lst.count)

# A função dir() mostra todos os métodos e atributos de um objeto
dir(lst)

a = " Isso é uma string"

print(a.split())