# -*- coding: utf-8 -*-
"""metodos2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11oI9yu4RyH8vF56v3lResCZ408Ug_zpi

Métodos
"""

# Criando uma classe chamada Circulo
class Circulo():
  # O valor de pi é constante
  pi = 3.14
  def __init__(self, raio = 5):
    self.raio = raio

  def area(self):
    return (self.raio * self.raio) * Circulo.pi
  def setRaio(self, novo_raio):
    self.raio = novo_raio
  def getRaio(self):
    return  self.raio

# Criando o objeto circ. Uma instância da classe Circulo()
circ = Circulo()

circ.getRaio()

# Criando outro objeto chamado circ1. Uma instância da classe Circulo()
# Agora sobrescrevendo o valor do atributo
circ1 = Circulo(7)

# Executando um método da classe Circulo
circ1.getRaio()

# Imprimindo o raio
print("O raio é : ", circ.getRaio())

# Imprimindo o raio
print("Area igual a: : ", circ.area())

# Gerando um novo valor para o raio do círculo
circ.setRaio(3)

# Imprimindo o novo raio
print('Novo raio igual a: ', circ.getRaio())