# -*- coding: utf-8 -*-
"""modulos-e-pacotes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SzFtPy0xEBjf64fFFYN2TkXQYf7l63XX

Módulos e pacotes
"""

# importando um módulo em python

import math

# verificando todos os métodos disponíveis no módulo
dir(math)

# usando um método do módulo math.
math.sqrt(25)

# importando apenas um método do módulo math

from math import sqrt

# usando o método
sqrt(9)

# imprimindo todos os métodos do módulo math.

print(dir(math))

# help do método sqrt do módulo math
help(math)

import random

random.choice(['maça', 'banana','laranja'])

random.sample(range(100),10)

import statistics

dados = [2.75, 1.75, 1.25, 0.25, 0.5, 1.25, 3.5]

statistics.mean(dados)

statistics.median(dados)

import os

os.getcwd()

print(dir(os))

import sys

sys.stdout.write('teste')

sys.version

print(dir(sys))

# Importando o módulo request do pacote urllib, usado para trazer url's 
# para dentro do nosso ambiente Python
import urllib.request

# Variável resposta armazena o objeto de conexão à url passada como 
# parâmetro
resposta = urllib.request.urlopen('http://python.org')

print(resposta)

# Chamando o método read() do objeto resposta e armazenando o código 
# html na variável html
html = resposta.read()

#imprimindo html
print(html)