# -*- coding: utf-8 -*-
"""numeros_operacoes_matematicas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/andersonss92/curso_python_dsa/blob/main/numeros_operacoes_matematicas.ipynb

Números e Operações matemáticas
"""

#SOMA
4 + 4

#SUBTRAÇÃO
4 - 3

#MULTIPLICAÇÃO
3 * 3

#DIVISÃO
3 / 2

#POTêNCIA
4 ** 2

#MÓDULO
10 % 3

"""FUNÇÃO TYPE"""

type(5)

type(5.0)

a = 'Eu sou uma string'
type(a)

"""Operações com números float:"""

3.1 + 6.4

4 + 4.0

4 + 4

# Resultado é um número float
4 / 2

# Resultado é um número inteiro
4 // 2

4 / 3.0

4 // 3.0

"""CONVERÇÃO"""

float(9)

int(6.0)

int(6.5)

"""HEXADECIMAL E BINÁRIO"""

hex(394)

hex(217)

bin(268)

bin(390)

"""FUNÇÕES ABS, ROUND E POW"""

# Retorna o valor absoluto
abs(-8)

# Retorna o valor absoluto
abs(8)

# Retorna o valor com arredondamento
round(3.14151922,2)

# Potência
pow(4,2)

# Potência
pow(5,3)

"""Fim!"""