# -*- coding: utf-8 -*-
"""objetos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Yaz_evoq0w27xo2I0mnMXQxp2hTMTLf

Objetos
"""

# criando uma lista:
lst_num = ["Data", "Science", "Academy","Nota", 10, 10]

type(lst_num)

lst_num.count(10)

# Usamos a função type, para verificar o tipo de um objeto
print(type(10))
print(type([]))
print(type(()))
print(type({}))
print(type("a"))

# Criando um novo tipo de objeto chamado Carro
class Carro(object):
  pass

# instância do carro
palio = Carro()

print(type(palio))

# Criando uma classe
class Estudantes:
  def __init__(self, nome, idade, nota):
    self.nome = nome
    self.idade = idade
    self.nota = nota

# Criando um objeto chamado Estudante1 a partir da classe Estudantes
Estudante1 = Estudantes("Pele", 12, 9.5)

print(Estudante1.nome)
print(Estudante1.idade)
print(Estudante1.nota)

# Criando uma classe
class Funcionários:
  def __init__(self, nome, salario):
    self.nome = nome
    self.salario = salario

  def listFunc(self):
    print("O nome do funcionário é"+ self.nome +"e o salário é R$" + str(self.salario))

# Criando um objeto chamado Func1 a partir da classe Funcionarios
Func1 = Funcionários("Obama", 20000)
Func2 = Funcionários("Merkel", 22000)
Func3 = Funcionários("Napoleão",18000)

# Usando o método da classe
Func1.listFunc()
Func2.listFunc()
Func3.listFunc()

print("**** Usando atribuitos ****")

hasattr(Func1, "nome")

hasattr(Func1, "salario")

setattr(Func1, "salario", 4500)

hasattr(Func1, "salario")

getattr(Func1, "salario")

delattr(Func1, "salario")

hasattr(Func1, "salario")