# -*- coding: utf-8 -*-
"""range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xR_DXbQhx0QjtpyzlfITeOLv-T86y_jf
"""

# Imprimindo números pares entre 50 e 101
for i in range(50, 101, 2):
  print(i)

for i in range (3, 6):
  print(i)

for i in range(0, -20, -2):
  print(i)

lista = ['Morango','Banana','Abacaxi','Uva']
lista_tamanho = len(lista)
for i in range(0, lista_tamanho):
  print(lista[i])

# Tudo em Python é um objeto
type(range(0,3))