# -*- coding: utf-8 -*-
"""reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aC9aZpWCop74NZPQHeR1lV8qvSjS_nvn

Reduce
"""

# Importando a função reduce do módulo functools
from functools import reduce

# criando uma lista
lista = [47,11,42,13]

lista

# Função:

def soma (a,b):
  x = a + b
  return x

# Usando reduce com uma função e uma lista. A função vai retornar o valor máximo
reduce(soma, lista)

from IPython.display import Image
Image ('/reduce.png')

lst = [47,11,42,13]



# reduce + lambda

reduce(lambda x,y: x+y,lst)

# podemos atribuir a função lambda a uma variável:

max_find2 = lambda a,b: a if (a > b) else b

type(max_find2)

# Reduzindo a lista até o valor máximo, através da função criada com a expressão lambda
reduce(max_find2, lst)