# -*- coding: utf-8 -*-
"""strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18lAVzHMY9Y5Vgm3ig6iBpfobhWFjYbu_

Criando uma String:
"""

# Uma única palavra
"Oi"

# Uma frase
"Criando uma string em Python"

# Podemos usar aspas duplas
"Podemos usar as aspas duplas ou simples para strings em Python"

# Podemos combinar aspas duplas ou simples
"Testando strings em 'Python'"

"""Imprimindo uma string"""

print ("Testando strings em Python")

print ("Testando\nstrings\nem\nPython")

print(\n)

"""Indexando strings"""

# Atribuindo uma string
s = 'Data Science Academy'

print(s)

# Primeiro elemento da string
s[0]

"""Aplicando slicing em strings"""

print('Utilizando slicing é possível fazer a leitura do código até um determinado ponto. Por exemplo: ')

s[5:]

s[:5]

s[:]

# Também podemos fazer a indexação negativa.
s[-1]

s[:-1]

s[::2]

s[::3]

s[::-1]

"""Propriedades de uma string"""

s

# Não podemos mudar strings
s[0] = 'x'

# Concatenando strings
s = s + ' é a melhor maneira de estar preparado para o mercado de trabalho em ciência de dados '

# Podemos usar multiplicação para fazer repetição.
letra='w'

letra*3

#Funções Built-in em Python
s

s.upper()

s.lower()

s.split()

# Dividir uma string a partir de um elemento específico.
s.split('y')

"""Funções String"""

a = 'seja bem vindo ao universo de Python!'

a.capitalize()

a.count('o')

a.find('y')

a.center(20, 'z')

a.isalnum()

a.isalpha()

a.islower()

a.isspace()

a.endswith('o')

a.partition('!')

"""Comparando Strings"""

print("Python" == "R")

print("Python" == "Python")