# -*- coding: utf-8 -*-
"""trabalhando-com-arquivos-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ec0ZdutedvHdcGtlMQEAxYroMY3lo-oV

Trabalhando com arquivos
"""

# abrindo arquivo para leitura

arq1 = open("arquivo1.txt", "r")

# Lendo o arquivo
print(arq1.read())

# contando o número de caracteres
print(arq1.tell())

# retorna ao inicio do arquivo.

print(arq1.seek(0,0,))

# leitura dos 10 primeiros caracteres do arquivo.

print(arq1.read(10))

"""Gravando Arquivos"""

# Abrindo o arquivo para gravação.

arq2 = open("arquivo1.txt", "w")

# Como o arquivo fo aberto para gravação não pode ser lido.
arq2 = open(arq2.read())

arq2.write("Testando gravação de arquivos em Python ")

arq2.close()

# Lendo arquivo gravado.

arq2 = open("arquivo1.txt", "r")

print(arq2.read())

# Acrescentando conteúdo ao arquivo
arq2 = open("arquivo1.txt", "a")

arq2.write(" Acrescentando conteúdo")

arq2.close()

arq2 = open("arquivo1.txt", "r")
arq2.read()

arq2.seek(0,0)

print(arq2.read())