# -*- coding: utf-8 -*-
"""tuplas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18v7IfdzpjbvSFMu5ajAwZAmDthdJ1rSo
"""

# criando uma tupla.
tupla1 = ("Geografia", 10, "Elefantes")

tupla1

#tuplas não suportam append.
tupla1.append("Chocolate")

#tuplas não suportam delete de 1 item em especifico. 
del tupla1("Gatos")

# tuplas podem ter um item só.
tupla1 = ("Chocolate")

tupla1

tupla1 = ("Geografia", 10, "Elefantes")

tupla1

tupla1[0]

#verificando o tamanho de uma tupla.
len(tupla1)

# slicing da mesma forma que se faz em listas.
tupla1[1:]

tupla1.index("Elefantes")

# tuplas não suportam atribuição de item.
tupla1[1] = 21

del tupla1

tupla1

t2 = ("A","B","C")

t2

t2 [0] = "D"

# usando a função list() para converter uma tupla em lista.
lista_t2 = list(t2)

lista_t2

lista_t2.append("D")

t2 = tuple(lista_t2)

t2