# -*- coding: utf-8 -*-
"""variaveis_operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uFaIw2AxqtosIYUidNxrdNjTIuEJn_1
"""

# Atribuindo um valor a variável e imprimindo a mesma na tela.
var_teste = 1
var_teste

# imprimindo o valor da variável na tela, via comando print.
print(var_teste)

# Não é possível imprimir uma variável que não foi declarada. Retorna em 'erro'.
# my_var

var_teste2 = 2
print(var_teste2)

type(var_teste2)

var_teste3 = 9.5
type(var_teste3)

x = 1
x

"""Declaração Multipla:"""

pessoa1, pessoa2, pessoa3 = "Maria" , "João", "Paulo"

pessoa1

pessoa2

pessoa3

fruta1 = fruta2 = fruta3 = "laranja"

fruta2

fruta3

"""Variáveis atribuídas a outras variáveis e ordem dos operadores"""

largura = 2

altura = 4

area = largura * altura

area

perimetro = 2 * altura + 2 * largura

perimetro

"""Operações com variáveis"""

idade1 = 25

idade2 = 35

idade3 = idade1 + idade2

idade2 - idade1

idade2 / idade1

idade2 % idade1

"""Concatenação de variáveis"""

nome = "Steve"

sobrenome = "Jobs"

fullname = nome + " " + sobrenome

fullname