# -*- coding: utf-8 -*-
"""zip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1heUJ8-_5mnReh9WQySyUUwgz6eFtpleA

Zip
"""

# criando duas listas
a = [1,2,3]
b = [4,5,6]

# Unindo as listas. Em Python3 retorna um iterator
zip(a,b)

# zip retorna tuplas, aqui é uma lista de tuplas.
list(zip(a,b))

# Atenção quando as sequências tiverem número diferente de elementos
list(zip('ABCD','xy'))

# criando duas listas:
a = [1,2,3]
b = [4,5,6,7,8]

list(zip(a,b))

# criando dois dicionários:
d1 = {'a': 1, 'b': 2}
d2 = {'c': 4, 'd': 5}

list(zip(d1,d2))

list(zip(d1,d2.values()))

# Criando uma função para trocar valores entre 2 dicionários
def trocaValores(d1,d2):
  dicTemp = {}

  for d1key, d2val in zip(d1,d2.values()):
    dicTemp[d1key] = d2val

    return dicTemp

trocaValores(d1, d2)